services:

  strawberry_fastapi:
    build:
      context: ./strawberry_fastapi
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]
    # container_name: strawberry_graphql_fastapi.org
    volumes:
      - ./strawberry_fastapi:/code/app
    ports:
      - 8080:80

  couchdb:
    image: couchdb:latest
    restart: always
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./couchdb/data:/opt/couchdb/data